## Pack Development Configuration

# Pack name for download/upload (e.g. PCK.CUSTOM_FOOBAR)
name: PCK.AUTOMIC_HELM

# location of the content source objects (default: ae/content)
source: ae/content

# location of the appdata source objects (default: ae/appdata)
appdata: ae/appdata
binaries: 
- object: RESOURCES/PCK.AUTOMIC_HELM.PRV.CUSTOM_TYPES
  timestamp: disabled
  resources: 
  - name: COMPONENT#HELM_CHART_CONTAINER#2
    type: TEXT
    path: ara/types/component/Helm Chart Container.xml
    version: 1.0.0
  - name: COMPONENT#HELM_CHART#3
    type: TEXT
    path: ara/types/component/Helm Chart.xml
    version: 1.0.0
  - name: DEPLOYMENTTARGET#KUBERNETES_CLUSTER#1
    type: TEXT
    path: ara/types/deploymenttarget/Kubernetes Cluster.xml
    version: 1.0.0
  - name: PACKAGE#HELM
    type: TEXT
    path: ara/types/package/Helm.xml
    version: 1.0.0
  - name: ARTIFACTSOURCE#HELM
    type: TEXT
    path: ara/types/artifact/Artifact Helm 1.0.0.xml
    version: 1.0.0
